# Generated by Django 4.0.7 on 2023-10-12 08:48

from django.db import migrations, models

def generate_id_for_old_posts(app, schema):
    Post = app.get_model("blog", "Post")
    id = 1
    for post in Post.objects.all():
        post.id = id
        post.save(updated_fields=["id"])
        id +=1

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_title'),
    ]

    operations = [

        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=False, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(generate_id_for_old_posts),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
